Docimax.Web_ICD/Controllers/HomeController.cs
using Docimax.Common;
using Docimax.Common_ICD;
using Docimax.Data_ICD.DAL;
using Docimax.Data_ICD.DAL.WebChat;
using Docimax.Interface_ICD.Enum;
using Docimax.Interface_ICD.Interface;
using Docimax.Interface_ICD.Interface.WebChat;
using Docimax.Interface_ICD.Model;
using Docimax.Interface_ICD.Model.WebChat;
using Docimax.Web_ICD.Models;
using JiebaNet.Segmenter;
using JiebaNet.Segmenter.PosSeg;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Docimax.Web_ICD.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "51ICD平台描述页面.";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "51ICD平台合同信息.";

            return View();
        }
        public ActionResult Detail()
        {
            return View();
        }

        public ActionResult ShowDetail()
        {
            return View();
        }

        public ActionResult Help()
        {
            return View();
        }
        public ActionResult Tools(ICDPagedList<CodeSearchModel, ICDModel> model)
        {
            model = initialList(model);
            return View(model);
        }

        public ActionResult ICDList(ICDPagedList<CodeSearchModel, ICDModel> model)
        {
            model = initialList(model);
            var itemsStr = JsonHelper.SerializeObject(model);
            return Content(itemsStr);
        }

        public ActionResult ICDViewModelList(ICDPagedList<CodeSearchModel, ICDViewModel> model)
        {
            model.Content = initialICDViewModelList(model);
            var itemsStr = JsonHelper.SerializeObject(model);
            return Content(itemsStr);
        }

        public PartialViewResult _Tools(ICDPagedList<CodeSearchModel, ICDModel> model)
        {
            model = initialList(model);
            return PartialView(model);
        }

        public ActionResult DropDownParial(ICDTypeEnum icdType, string dropDownListName)
        {
            ViewData["ddlName"] = dropDownListName;
            IService access = new DAL_Service();
            Dictionary<int, string> items = access.GetICDVersion(icdType);
            var selectList = new SelectList(items, "Key", "Value");
            return PartialView(selectList);
        }

        public ActionResult ICDDetail(ICDTypeEnum icdType, int icdDetailID)
        {
            IICDRepository access = new DAL_ICDRepository();
            var model = access.GetICDModel(icdDetailID, icdType);
            if (model != null)
            {
                model.ICDType = icdType;
            }
            return View(model);
        }

        public ActionResult GetICDDetail(ICDTypeEnum icdType, int icdDetailID)
        {
            IICDRepository access = new DAL_ICDRepository();
            var model = access.GetICDModel(icdDetailID, icdType);
            var modelStr = JsonHelper.SerializeObject(model);
            return Content(modelStr);
        }

        public ActionResult CanEdit()
        {
            if (User == null || User.Identity == null || string.IsNullOrWhiteSpace(User.Identity.GetUserId()))
            {
                return Content("false");
            }
            return Content("true");
        }


        #region 私有方法

        private List<ICDViewModel> initialICDViewModelList(ICDPagedList<CodeSearchModel, ICDViewModel> model)
        {
            if (model != null && model.TextFilter != null && model.TextFilter.Contains('-'))
            {
                model.TextFilter = model.TextFilter.Split('-')[0];
            }
            saveSearchLog(model);
            var result = ICDVersionList.GetICDViewModelList(model.TextFilter, model.SearchModel.ICDType.GetHashCode());
            model.TotalRecords = result.Count();
            result = result.Skip((model.Page - 1) * model.PageSize)
                    .Take(model.PageSize).ToList();
            return result;
        }
        private ICDPagedList<CodeSearchModel, ICDModel> initialList(ICDPagedList<CodeSearchModel, ICDModel> model)
        {
            if (model == null)
            {
                model = new ICDPagedList<CodeSearchModel, ICDModel>();
            }
            if (model.SearchModel == null)
            {
                model.SearchModel = new CodeSearchModel { ICDType = ICDTypeEnum.诊断编码, IcdVersionID = 1 };
            }
            saveSearchLog(model);
            IService access = new DAL_Service();
            Dictionary<int, string> items = access.GetICDVersion(model.SearchModel.ICDType);
            if (model.SearchModel.IcdVersionID == 0 && items != null && items.Count > 0)
            {
                model.SearchModel.IcdVersionID = items.FirstOrDefault().Key;
            }
            var selectList = new SelectList(items, "Key", "Value");
            ViewData["IcdVersion"] = selectList;
            model.Content = buildICDList(model);
            return model;
        }
        private List<ICDModel> buildICDList(ICDPagedList<CodeSearchModel, ICDModel> model)
        {
            if (model != null && model.TextFilter != null && model.TextFilter.Contains('-'))
            {
                model.TextFilter = model.TextFilter.Split('-')[0];
            }
            var result = ICDVersionList.GetICDList(model.SearchModel.IcdVersionID, model.TextFilter);
            model.TotalRecords = result.Count();
            result = result.Skip((model.Page - 1) * model.PageSize)
                    .Take(model.PageSize).ToList();
            return result;
        }

        private void saveSearchLog(ICDPagedList<CodeSearchModel, ICDModel> model)
        {
            if (model != null)
            {
                var logModel = new WebChatUserSearchLog
                {
                    SearchFilter = model.TextFilter,
                };
                if (model.SearchModel != null)
                {
                    if (!string.IsNullOrWhiteSpace(model.SearchModel.ICDSessionKey))
                    {
                        if (HttpRuntime.Cache[model.SearchModel.ICDSessionKey] != null && (HttpRuntime.Cache[model.SearchModel.ICDSessionKey] is WebChatSession))
                        {
                            var webChatSession = HttpRuntime.Cache[model.SearchModel.ICDSessionKey] as WebChatSession;
                            logModel.OpentId = webChatSession.openid;
                        }
                    }
                    if (model.TextFilter!=null&&!model.TextFilter.Trim().Contains(" "))
                    {
                        var jbSeg = new JiebaSegmenter();
                        jbSeg.LoadUserDict(Path.Combine(ConfigManager.ConfigFileBaseDir, "51ICDdict.txt"));
                        var posSeg = new PosSegmenter(jbSeg);
                        var tokens = posSeg.Cut(model.TextFilter.ToUpper(), true);
                        var segmentResult = string.Join(" ", tokens.Select(token => string.Format("{0} ", token.Word, token.Flag))).Trim();
                        model.TextFilter = segmentResult;
                        logModel.SegmentResult = segmentResult;
                    }
                    logModel.ICDVersionID = model.SearchModel.IcdVersionID == 0 ? -1 : model.SearchModel.IcdVersionID;
                    logModel.ICDVersionType = model.SearchModel.ICDType.GetHashCode();
                }
                ThreadPool.QueueUserWorkItem(_ =>
                {
                    IWebChatUserSearchLog logAccess = new DAL_WebChatUserSearchLog();
                    logAccess.InsertUserSearchLog(logModel);
                });
            }
        }

        private void saveSearchLog(ICDPagedList<CodeSearchModel, ICDViewModel> model)
        {
            var newModel = new ICDPagedList<CodeSearchModel, ICDModel>
            {
                SearchModel = model.SearchModel,
                TextFilter = model.TextFilter,
            };
            saveSearchLog(newModel);
            model.TextFilter = newModel.TextFilter;
        }

        #endregion
    }
}

Docimax.Web_ICD/Controllers/ICDController.cs
using Docimax.Data_ICD.DAL;
using Docimax.Interface_ICD.Interface;
using Docimax.Interface_ICD.Model;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;

namespace Docimax.Web_ICD.Controllers
{
    public class ICDController : Controller
    {
        public ActionResult UpdateICDSummary(ICDModel model)
        {
            var userID = User.Identity.GetUserId();
            IICDRepository access = new DAL_ICDRepository();
            var icdExcuteResult = access.UpdateICDSummary(model,userID);
            return Json(icdExcuteResult);
        }
    }
}

Docimax.Web_ICD/Views/Home/About.cshtml
@{
    ViewBag.Title = "联系我们";
}
<h2>@ViewBag.Title</h2>

<p>51ICD是影研科技致力于病案质量控制的服务平台，努力打造一个及病案首页、病案内容和首页编码的含形式上、简单逻辑和专业的医学知识为基础的编码服务的服务供需平台。</p>
<p>平台正在内部测试中，如果您有意向，请联系我们：</p>
<p>邮箱：51icd@docimax.com.cn</p>

Docimax.Web_ICD/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "用户协议";
}
<h2>@ViewBag.Title.</h2>



<address>
    <strong>获取支持和帮助:</strong>   <a href="mailto:51ICD@docimax.com.cn">51ICD@docimax.com.cn</a>
</address>

Docimax.Web_ICD/Views/Home/Detail.cshtml
@{
    ViewBag.Title = "产品详细";
}

<div class="jumbotron">
    <h1>51ICD</h1>
    <p>
        随着医疗改革的深入，基于DRGs的医保付费和医疗质量评测体系也已经在全国范围内逐步展开；而病案质控和病案首页的准确编码是推广和应用DRGs的重中之重。
    </p>
    <p>
        51ICD编码平台提供了基于脱敏病案的病案首页形式质控和病案首页编码等服务，基于云端为质控和编码能力不足或者峰值能力不足的医院提供专业的相关服务，节约院方运营成本，提供病案整体质量，拥抱DRGs的推广和新医改的深化。
    </p>
</div>
<div class="row">
    <div class="col-md-12">
        <a name="kk1" id="kk1" class="anchor"></a>
        <h2>病案首页形式质控</h2>
        <p>
            现在病案室医生很大一部分精力都在病案首页的缺失项和简单逻辑错误项的检查上面，这种简单重复的体力劳动使得病案医生没有更多的精力放到专业的病案内容质控，编码和基于高质量的病案首页数据进行统计分析对医院的经营决策提供更权威的建议和意见。
        </p>
        <p>
            51ICD除提供简单的缺项检查外，通过维护一个简单逻辑的知识库，此处的简单逻辑指不需要专业的医学知识就能判断出来的逻辑，比如性别与有些诊断不能同时出现等；由于是基于云端维护的知识库，是一个增量的过程，一种新知识的增加惠及所有接入平台的医院。
        </p>
        <p>@Html.ActionLink("去试试 >>", "ShowDetail", "Home", new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-12">
        <a name="kk2" id="kk2" class="anchor"></a>
        <h2>病案内容形式质控</h2>
        <p>指对病案内的项目进行的简单逻辑缺项检查和病历项目排序</p>
        <p>病案内项目简短逻辑缺项检查是维护一个针对于病案项目的的知识库，根据病案项目的依赖关系，确定哪些项目缺失，比如缺失病程记录，体温单等。</p>
        <p>病历项目排序</p>
        <p>@Html.ActionLink("去试试 >>", "ShowDetail", "Home", new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-12">
        <a name="kk3" id="kk3" class="anchor"></a>
        <h2>病案首页编码服务</h2>
        <div>
            <p>
                主要针对于影响DRGs入组的各个项目主要诊断，次要诊断，并发症，合并症，主要操作，次要操作等进行精确选择和补充，上述各项以建议的方式给出，提高DRGs入组的准确和精确。
            </p>
            <p>
                上述各项是基于通读病历的各个内容给出的合理建议，其中并发症和合并症以次要诊断的形式给出。
            </p>
            <p>
                右图形象的提现了上述编码结果对DRGs入组的影响，精确的编码结果能够更精确的落入到合适的DRGs的组合中，对医疗报销和相关评测例如CMI等产生巨大的影响。
            </p>
        </div>
        <div class="col-md-7">
            <img src="~/Img/DRGsEP.jpg" width="300" height="300" class="img-responsive" alt="Responsive image">
        </div>
    </div>
</div>

Docimax.Web_ICD/Views/Home/DropDownParial.cshtml
@model SelectList
@Html.DropDownList(ViewData["ddlName"].ToString(), Model, new { @class = "form-control" })

Docimax.Web_ICD/Views/Home/Help.cshtml
@{
    ViewBag.Title = "帮助";
}
<h2>@ViewBag.Title</h2>

<p>51ICD是影研科技致力于病案质量控制的服务平台，努力打造一个集病案首页、病案内容和首页编码全方位的，涵盖形式上、简单逻辑和专业编码的质控供需平台。</p>
<p>平台正在内部测试中，现诚招首批内测用户，内测用户会获得更高的编码收益，名额有限，望有志于提高国内病案质量的同仁和专家老师，速速联系我们：</p>
<p>邮箱：zhangh@docimax.com.cn</p>

Docimax.Web_ICD/Views/Home/ICDDetail.cshtml
@{
    ViewBag.Title = "icd编码详情";
}
@model Docimax.Interface_ICD.Model.ICDModel
@if (Model != null)
{
    @Html.HiddenFor(model => model.ICDID);
    @Html.HiddenFor(model => model.ICDType);
    @Html.HiddenFor(model => model.LastModifyStamp);
    <h4>@Model.DisplayText</h4>
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <form class="form-horizontal" role="form" id="form_Summary">
        <div class="form-group">
            @Html.AntiForgeryToken()
            @if (!string.IsNullOrWhiteSpace(Model.ICD_Description))
            {
                <div class="col-md-11" id="summaryDiv">
                    @Model.ICD_Description
                </div>
                <div class="col-md-1">
                    <input id="btnSummary" type="button" class="btn btn-primary" value="编辑摘要" />
                </div>
            }
            else
            {
                <div class="col-sm-11" id="summaryDiv">
                    <p>暂无摘要</p>
                </div>
                <div class="col-sm-1">
                    <input id="btnSummary" type="button" class="btn btn-primary" value="添加摘要" />
                </div>
            }
        </div>
    </form>
    <hr />
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="DetailDescription">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" href="#collapseDetailDescription" aria-expanded="true" aria-controls="collapseDetailDescription">
                    详细描述
                </a>
            </h4>
        </div>
        <div id="collapseDetailDescription" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="DetailDescription">
            <div class="panel-body">
                @if (!string.IsNullOrWhiteSpace(Model.DetialDescription))
                {
                    <div class="col-md-10">
                        @Model.DetialDescription
                    </div>
                    <div class="col-md-1">
                        @*<input type="button" class="btn btn-primary" value="去添加" />*@
                    </div>
                }
                else
                {
                    <div class="col-md-10">
                        暂无详细描述
                    </div>
                    <div class="col-md-1">
                        @*<input type="button" class="btn btn-primary" value="去添加" />*@
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="Datalink">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" href="#collapseDatalink" aria-expanded="true" aria-controls="collapseDatalink">
                    资料链接
                </a>
            </h4>
        </div>
        <div id="collapseDatalink" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="Datalink">
            <div class="panel-body">
                @if (Model.DataLinks != null && Model.DataLinks.Count > 0)
                {
                    <div>@Model.DetialDescription</div>
                }
                else
                {
                    <div class="col-md-11">
                        暂无资料链接
                    </div>
                    <div class="col-md-1">
                        @*<input type="button" class="btn btn-primary" value="去添加" />*@
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="editLog">
            <h4 class="panel-title">
                <a class="accordion-toggle collapsed" data-toggle="collapse" href="#collapseEditLog" aria-expanded="false" aria-controls="collapseEditLog">
                    编辑记录
                </a>
            </h4>
        </div>
        <div id="collapseEditLog" class="panel-collapse collapse" role="tabpanel" aria-labelledby="editLog">
            <div class="panel-body">
                @if (Model.OperateLogs != null && Model.OperateLogs.Count > 0)
                {
                    <div>@Model.OperateLogs</div>
                }
                else
                {
                    <div class="col-md-12">
                        暂无编辑记录
                    </div>
                }
            </div>
        </div>
    </div>
}
else
{
    <h2>未找到相关记录</h2>
}
<script type="text/javascript">
    var isSummaryEdite = false;
    var summaryText= '@Html.TextBoxFor(e => e.ICD_Description,
    new { @class = " form-control",
          @placeholder = "摘要信息",
          @style = "max-width:100%"
    })';
    var summaryValue='@Model.ICD_Description';
    var summaryStamp='@Model.LastModifyStamp';
    $('#btnSummary').click(function () {
        if (!isSummaryEdite) {
            $.ajax({
                url: '@Url.Action("CanEdit", "Home")',
                datatype: "text",
                type: "post",
                success: function (data) {
                    if ('true' != data) {
                        $('#loginLink').click();
                    }
                    else {
                        $('#summaryDiv').html(summaryText);
                        $('#ICD_Description').val(summaryValue);
                        $('#btnSummary').val("保存摘要");
                        isSummaryEdite = true;
                    }
                }
            });
        }
        else {
            $.ajax({
                url: '@Url.Action("UpdateICDSummary", "ICD")',
                datatype: "text",
                type: "post",
                data: {
                    ICDType: '@Model.ICDType',
                    ICDID:@Model.ICDID,
                    ICD_Description: $("#ICD_Description").val(),
                    LastModifyStamp:summaryStamp,
                },
                success: function (data) {
                    if (data.IsSuccess) {
                        summaryValue= $("#ICD_Description").val();
                        $('#summaryDiv').html(summaryValue);
                        summaryStamp=data.TResult;
                        $("#btnSummary").val("编辑摘要");
                        isSummaryEdite = false;
                    }
                    else {
                        showError(data.ErrorStr);
                    }
                }
            });
        }
    });   

    function reposition() {
        var modal = $(this),
            dialog = modal.find('.modal-dialog');
        modal.css('display', 'block');
        dialog.css("margin-top", Math.max(0, ($(window).height() - dialog.height()) / 3));
        dialog.css("max-width", '460px');
    }

    $('.modal').on('show.bs.modal', reposition);

    $(window).on('resize', function () {
        $('.modal:visible').each(reposition);
    });

    var timer = null;
</script>
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/sitePubJS")

Docimax.Web_ICD/Views/Home/Index.cshtml
@{
    ViewBag.Title = "主页";
}

<div class="jumbotron">
    <h1>51ICD</h1>
    <p>
        是一个基于<span class="label label-warning">去隐私化的病案</span>提供不同病案质控服务的平台，可以根据医院的现状提供差别化的病案质控服务。自动化的形式质控使现在病案室的医生从大量重复的体力劳动中解放出来；
        基于内容的首页编码服务一方面提供现有病案的数据完整性和可靠性，另一方面也可与现有编码医生进行相互学习和提高，解决病案峰值的压力，保证编码质量。
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>病案首页形式质控</h2>
        <p>
            不仅仅提供简单的缺项检查，还会自动完成简单的一些逻辑上非专业知识的质控，解放病案室医生的体力劳动，使他们把更多的精力放到能应用专业技能的工作上来.
        </p>
        <p>@Html.ActionLink("了解更多 >>", "Detail", "Home", "http", @Request.Url.Host, "kk1", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>病案内容形式质控</h2>
        <p>病案内容项目缺项检查和排序，保证病案内容的完整性，为后续的编码服务提供基础的数据完整性保证</p>
        <p>@Html.ActionLink("了解更多 >>", "Detail", "Home", "http", @Request.Url.Host, "kk2", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>病案首页编码服务</h2>
        <p>为由编码需求的医院和有资质、能力的编码员搭建的一个服务供需平台，提高医院的编码质量的同时为有专业技能的编码员提供了一个新的提现能力价值的平台，达到双赢甚至多赢的局面.速度，</p>
        <p>@Html.ActionLink("了解更多 >>", "Detail", "Home", "http", @Request.Url.Host, "kk3", null, new { @class = "btn btn-default" })</p>
    </div>
</div>

Docimax.Web_ICD/Views/Home/ShowDetail.cshtml
@{
    ViewBag.Title = "功能建设中";
}

<h2>该功能正在内部测试中，敬请期待！！！</h2>

Docimax.Web_ICD/Views/Home/Tools.cshtml
@using Docimax.Interface_ICD.Model
@using PagedList.Mvc
@using Docimax.Common
@using Docimax.Interface_ICD.Enum

@model ICDPagedList<CodeSearchModel, ICDModel>
@{
    ViewBag.Title = "icd字典查询";
}
<script type="text/javascript" src="~/Scripts/typeahead.bundle.js"></script>
<script type="text/javascript" src="~/Scripts/handlebars.js"></script>
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        listenRadioIdClick();
        $("input[name='id']:first").trigger('click');

        $('.form-control.icd').typeahead({
            hint:false,
            highlight: false,
        },
        {
            name: 'icdSuggestion',
            display: 'DisplayText',
            source: function (query, syncResults, asyncResults) {
                var icdVersionID = $('#SearchModel_IcdVersionID').val();
                $.post('/Dictionary/ICD_Diagnosis_Typeahead', { queryStr: query, icdVersionID: icdVersionID }, function (data) {
                    asyncResults(data)
                });
            },
            templates: {
                suggestion: Handlebars.compile('<div><strong>{{ICD_Code}}</strong> – {{ICD_Name}}</div>')
            }
        });

        function listenRadioIdClick() {
            var ddlProbeUrl = '@Url.Action("DropDownParial")';
            $("input[name='SearchModel.ICDType']").click(function () {
                var id = $(this).val();
                console.log(id);
                $("#ICDType").val(id);
                $.get(ddlProbeUrl, { icdType: id, dropDownListName: "SearchModel.IcdVersionID" }, function (data) {
                    $("#SearchModel_IcdVersionID").replaceWith(data);
                });
            });
        }
    });
</script>
<h4>@ViewBag.Title</h4>
<hr />
@using (Html.BeginForm("Tools", "Home", FormMethod.Get))
{
    <div class="row">
        <div class="col-sm-11">
            <div class="form-inline">
                <div class="radio">
                    <label style="font-size:16px;">
                        @Html.RadioButtonFor(model => model.SearchModel.ICDType, ICDTypeEnum.诊断编码, new { }) @ICDTypeEnum.诊断编码.ToString()
                    </label>
                    <input type="hidden" id="ICDType" value="诊断编码" />
                </div>
                <div class="radio">
                    <label style="font-size:16px;">
                        @Html.RadioButtonFor(model => model.SearchModel.ICDType, ICDTypeEnum.手术及操作编码, new { })@ICDTypeEnum.手术及操作编码.ToString()
                    </label>
                </div>
                @Html.DropDownListFor(model => model.SearchModel.IcdVersionID, (IEnumerable<SelectListItem>)ViewData["IcdVersion"], new { @class = "form-control" })
                @Html.TextBoxFor(model => model.TextFilter, new { @class = "form-control icd", @placeholder = "请输入名称、拼音简码或编码" })
                小提示：多个关键字可以空格分开，会有意外的效果哦 例如：<mark>急性 甲型 肝炎</mark>
            </div>
        </div>
        <div class="pull-right col-lg-1">
            <button class="btn btn-default" type="button" onclick="search(1);">
                查询
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>
        </div>
    </div>
}
<div style="margin-top:17px;" id="ICDResult">
</div>
<!--page start-->
<div class="row">
    <div class="col-md-12" style="margin-top:0px;">
        <input type="hidden" value="@Model.PageScript" id="pagelist" />
        <div class="pull-right" id="pageManage">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
     小广告：如果您有病案管理的相关需求，请联系400-690-0167或者销售张经理 13810146611
    </div>
</div>
<!--page end-->

<script type="text/javascript">
    function search(pageIndex) {
        //分页参数
        var PageSize = 10;
        $.ajax({
            url: '@Url.Action("_Tools", "Home")',
            data: {
                PageSize: PageSize,
                PageIndex: pageIndex,
                TextFilter: $("#TextFilter").val(),
                SearchModel: { IcdVersionID: $('#SearchModel_IcdVersionID').val(), ICDType: $("#ICDType").val() }
            },
            datatype: "text",
            type: "post",
            success: function (data) {
                $("#ICDResult").html(data);
                var aa = $("#pagelist").val();
                $("#pageManage").html(aa);
            }
        });
    }
</script>

Docimax.Web_ICD/Views/Home/_Tools.cshtml
@using Docimax.Interface_ICD.Model
@using PagedList.Mvc
@using Docimax.Common
@using Docimax.Interface_ICD.Enum
@model ICDPagedList<CodeSearchModel, ICDModel>
<input type="hidden" value="@Model.PageScript" id="pagelist" />
@{
    if (Model != null && Model.Content.Count > 0)
    {
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th class="col-md-5">名称</th>
                    <th class="col-md-4">编码</th>
                    <th class="col-md-3">详情</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Content)
                {
                    <tr>
                        <td style="vertical-align:middle"><a href='@Url.Action("ICDDetail", "Home", new { icdType = @Model.SearchModel.ICDType, icdDetailID = @item.ICDID })'>@item.ICD_Name</a></td>
                        <td style="vertical-align:middle"><a href='@Url.Action("ICDDetail", "Home", new { icdType = @Model.SearchModel.ICDType, icdDetailID = @item.ICDID })'>@item.ICD_Code</a></td>
                        <td>
                            <a href="@Url.Action("ICDDetail", "Home", new { icdType = @Model.SearchModel.ICDType, icdDetailID = @item.ICDID })" class="btn btn-default">
                                查看
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h2>未查到相关记录</h2>
    }
}