Docimax.Web_ICD/Controllers/UnRobItemController.cs
using Docimax.Data_ICD.DAL;
using Docimax.Interface_ICD.Enum;
using Docimax.Interface_ICD.Interface;
using Docimax.Interface_ICD.Model;
using Microsoft.AspNet.Identity;
using System;
using System.Web.Mvc;

namespace Docimax.Web_ICD.Controllers
{
    [Authorize]
    public class UnRobItemController : Controller
    {
        // GET: UnRobItem
        public ActionResult Index(ICDTimePagedList<CodeOrderSearchModel, CodeOrderModel> model)
        {
            if (model.SearchModel == null)
            {
                model.SearchModel = new CodeOrderSearchModel { OrderState = ICDOrderState.待抢单 };
            }
            model.SearchModel.UserID = User.Identity.GetUserId();
            ICode_Order access = new DAL_Code_Order();
            model = access.GetUnClaimOrderList(model);
            return View(model);
        }

        public ActionResult Claim(int orderID, string stamp, OrderTypeEnum orderType)
        {
            ICode_Order access = new DAL_Code_Order();
            var result = access.ClaimCodeOrder(User.Identity.GetUserId(), stamp, orderID);
            if (result.IsSuccess)
            {
                return RedirectToAction("Code", "ServiceItem", new { orderID = orderID, orderType = orderType });
            }
            return Content(result.ErrorStr);
        }
    }
}

Docimax.Web_ICD/Views/UnRobItem/Index.cshtml
@using Docimax.Interface_ICD.Model
@model ICDTimePagedList<CodeOrderSearchModel, CodeOrderModel>

@{
    ViewBag.Title = "编码抢单列表";
}
<h2>@ViewBag.Title</h2>
<div style="margin-top:17px;">
    @if (Model != null && Model.Content != null)
    {
        var grid = new WebGrid(
                   canPage: true,
                   rowsPerPage: Model.PageSize,
                   canSort: true,
                   ajaxUpdateContainerId: "grid");

        grid.Bind(Model.Content, rowCount: Model.TotalRecords, autoSortAndPage: false);
        grid.Pager(WebGridPagerModes.All);

        @grid.GetHtml(htmlAttributes: new { id = "grid" },   // id for ajaxUpdateContainerId parameter
            fillEmptyRows: false,
            tableStyle: "table table-bordered table-hover",
            firstText: "第一页",
            previousText: "上一页",
            nextText: "下一页",
            lastText: "最后一页",
            mode: WebGridPagerModes.All,
            columns: grid.Columns(
                                 grid.Column("PlatformOrderCode", "订单号", style: "col-lg-3", canSort: false),
                                 grid.Column("ORGName", "订单所属医院", style: "col-lg-4", canSort: false),
                                 grid.Column("Createtime", header: "创建时间", format: @<text>@item.Createtime.ToString("yyyy-MM-dd") </text>, canSort: false),
                                 grid.Column(header: "操作", canSort: false, style: "action",
                format: @<text>
                                    <a href="@Url.Action("Claim", "UnRobItem", new { orderID = @item.CodeOrderID, stamp = @item.LastModifyStamp, orderType = @item.OrderType })" class="btn btn-default">
                                        领单
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                    </a>
                </text>)));
    }
    else
    {
        //todo  提示没有数据
    }
</div>