Docimax.Web_ICD/Controllers/RoleAdminController.cs
using Docimax.Web_ICD.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Net;

namespace Docimax.Web_ICD.Controllers
{
    [Authorize(Roles = "DocimaxAdmins")]
    public class RoleAdminController : Controller
    {
        public RoleAdminController()
        {
        }

        public RoleAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public ActionResult Index()
        {
            return View(RoleManager.Roles);//显示角色清单
        }

        //异步读取角色详情
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // 读取角色内的用户列表。
            var users = new List<ApplicationUser>();
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }
            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }
        //
        //读取角色创建
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //异步写入角色创建
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
        //
        //异步读取角色编辑
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //异步写入角色编辑
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Docimax.Web_ICD/Controllers/UsersAdminController.cs
using System.Data.Entity;
using System.Net;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using Docimax.Web_ICD.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Mvc;

namespace Docimax.Web_ICD.Controllers
{
    [Authorize(Roles = "DocimaxAdmins")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }
        //
        //异步读取用户详情
        //GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            //用户为空时返回400错误
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //按Id查找用户
            var user = await UserManager.FindByIdAsync(id);
            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);
            return View(user);
        }
        //
        //读取用户编辑
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var userRoles = await UserManager.GetRolesAsync(user.Id);
            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }
        //
        //写入用户编辑
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")]EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);
                selectedRole = selectedRole ?? new string[] { };
                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "操作失败。");
            return View();
        }
    }
}

Docimax.Web_ICD/Views/Shared/MenuList.cshtml
@model List<Docimax.Interface_ICD.Model.ICDMenu>

<div class="navbar-header icd">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target="#icd-navbar-collapse">
        <span class="sr-only">切换导航</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    @Html.ActionLink("51icd", "Index", "Home", null, new { @class = "navbar-brand icd" })
</div>
<div class="collapse navbar-collapse" id="icd-navbar-collapse">
    <ul class="nav navbar-nav icd ">
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <li>@Html.ActionLink(item.DisplayName, item.ActionName, item.ControllerName)</li>
            }
        }
        else
        {
            <li>@Html.ActionLink("主页", "Index", "Home")</li>
            <li>@Html.ActionLink("关于", "About", "Home")</li>
            <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
        }
        @*通过身份验证并确认用户属于Admin角色显示管理菜单   后期需要单独站点来做管理后台*@
        @if (Request.IsAuthenticated && User.IsInRole(Docimax.Common_ICD.ConstStr.PlatformRoleName))
        {
            <li>@Html.ActionLink("实名认证管理", "Index", "ManageUserVeirfy")</li>
            <li>@Html.ActionLink("银行卡认证管理", "Index", "ManageBankCard")</li>
            <li>@Html.ActionLink("服务认证管理", "Index", "ManageUserService")</li>
            <li>@Html.ActionLink("用户管理", "Index", "UsersAdmin")</li>
            <li>@Html.ActionLink("角色管理", "Index", "RoleAdmin")</li>
        }
    </ul>
    @Html.Partial("_LoginPartial")
</div>

Docimax.Web_ICD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="icdApp">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1" />
    <meta name=viewport content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="keywords" content="51icd,ICD,ICD编码,ICD-9,ICD-10,ICD编码,icd编码查询">
    <meta name="description" content="51icd-专业的编码平台">
    <title>@ViewBag.Title - 51ICD</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <!--[if lte IE 7]>
          <script>location.href='http://www.51icd.com/upgrade-your-browser.html'</script>
    <![endif]-->

</head>
<body>
    <nav class="navbar navbar-default icd" role="navigation">
        <div class="container-fluid icd">
            @{Html.RenderAction("MenuList", "Account");}
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <div>
                <p>
                    Copyright &copy; @DateTime.Now.Year 北京影研创新科技发展有限公司
                </p>
                <p>
                    京ICP备12045562号 京公网安备110105008151号
                </p>
            </div>

        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <div class="modal fade " id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div id="LoginModalView" class="modal-content">

            </div>
        </div>
    </div>
    <script type="text/javascript">
        $('#loginLink').click(function () {
            $.ajax({
                url: '@Url.Action("ModalLogin", "Account")',
                datatype: "text",
                type: "get",
                async: true,
                data: {
                    returnUrl: GetUrlRelativePath()
                },
                success: function (loginView) {
                    $('#LoginModalView').html(loginView);
                    $("#LoginModal").modal('show');
                }
            });
        });
        function GetUrlRelativePath() {
            var url = document.location.toString();
            var arrUrl = url.split("//");
            var start = arrUrl[1].indexOf("/");
            var relUrl = arrUrl[1].substring(start);
            return relUrl;
        }
    </script>
</body>

</html>