Docimax.Web_ICD/Controllers/VerificationCodeController.cs
using Docimax.Common;
using System.Web.Mvc;

namespace Docimax.Web_ICD.Controllers
{
    public class VerificationCodeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return PartialView();
        }

        [AllowAnonymous]
        public ActionResult GetNewValidateCode(string validateKey)
        {
            var verrifyCodeModel = ValidateCodeHelper.CreateValidateCode(validateKey);
            return File(verrifyCodeModel.ValidateImage, @"image/jpeg");
        }
        [AllowAnonymous]
        public ActionResult VerifyValidateCode(string validateKey,string validateCode)
        {
            var verifyResult = ValidateCodeHelper.VerifyValidateCode(validateKey, validateCode);
            return Content(verifyResult.ToString());
        }
    }
}

Docimax.Web_ICD/Views/VerificationCode/Index.cshtml
<div class="modal  fade" id="verifyCodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">请输入下图中的验证码</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <input id="valiKey" type="hidden" value="" />
                    <div class="col-md-6">
                        <input id="valicodetxt" class="form-control" type="text"  placeholder="请输入右侧验证码">
                    </div>
                    <div class="col-md-6">
                        <img id="valiCode" style="cursor: pointer;" alt="验证码" title="看不清，点击换一张" />
                        <label class="control-label" id="lbl_refresh" style="cursor: pointer;"> <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> 看不清？点击换一张</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-default" value="确定" disabled="disabled" id="validateSubmitBtn"  />
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {

        var getValidateCode = function () {
            uuid = guid();
            $("#valiKey").val(uuid);
            var newSrc = "@Url.Action("GetNewValidateCode", "VerificationCode")?validateKey=" + uuid;
            $("#valiCode").attr("src", newSrc);
        }

        getValidateCode();

        $("#valiCode").click(getValidateCode);
        $("#lbl_refresh").click(getValidateCode);

        $("#valicodetxt").keyup(function () {
            if (this.value.length == 6) {
                $.ajax({
                    url: "@Url.Action("VerifyValidateCode", "VerificationCode")",// 跳转到 action
                    data: {
                        validateKey: $("#valiKey").val(),
                        validateCode: $("#valicodetxt").val()
                    },
                    type: 'post',
                    cache: false,
                    success: function (data) {
                        if (data == "True") {
                            $("#submitBtn").removeAttr("disabled");
                        }
                        //else {
                        //    getValidateCode();
                        //}
                    },
                    //error: function () {
                    //    alert("异常！");
                    //}
                })
            }
        });
    });

    function guid() {
        function s4() {
            return Math.floor((1 + Math.random()) * 0x10000)
              .toString(16)
              .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
          s4() + '-' + s4() + s4() + s4();
    }
</script>